---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend_deployment
spec:
  strategy:
    type: RollingUpdate
  replica: 1
  selector:
    matchLabels:
      app: frontend_UI_app
  template:
    metadata:
      name: UI_pod
      labels:
        app: frontend_UI_app
    spec:
      containers:
        name: javawebappcont
        image: ashokit/javawebapp
        ports:
        - port: 80
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
spec:
  type: LoadBalancer
  selector:
    app: frontend_UI_app
  ports:
    port: 80
    targetPort: 8080
...
